### ISSUE TITLE
Hello.its not working again

### ISSUE THREAD

**Issue by masoomdil** [Ne-Lexa/google-play-scraper#33] opened 2022-08-11 20:06 UTC
Hello.
Check that you use the latest version of the library.

_Originally posted by @Ne-Lexa in https://github.com/Ne-Lexa/google-play-scraper/issues/28#issuecomment-1165488911_

**Comment by masoomdil** [comment] 2022-08-13 07:48
yes i used new library but i am still getting 500 error

**Comment by Ne-Lexa** [comment] 2022-08-19 07:02
Duplicate of #32

**Closed by Ne-Lexa** 2022-08-19 07:02 UTC
