### ISSUE TITLE
Unable to get review

### ISSUE THREAD

**Issue by tompradana** [Ne-Lexa/google-play-scraper#35] opened 2022-08-13 09:03 UTC
Hello, 

I have used your code 10 days ago and it works very well. Thank you, your app is really awesome!

Today I tried again but there seems to be a change in the google play store website, so this application cannot display data. After I checked it, I got a notice like this:

`PHP Notice:  Trying to access array offset on value of type null in .../vendor/nelexa/google-play-scraper/src/Scraper/Extractor/ReviewsExtractor.php on line 55`

What should I do? Can I skip the review section?

**Comment by Ne-Lexa** [comment] 2022-08-19 07:03
Duplicate of #32

**Closed by Ne-Lexa** 2022-08-19 07:03 UTC
